server:
  port: ${PORT:8082}

spring:
  application:
    name: events-service

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:kafka:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:cinemaabyss-events}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  kafka:
    topics:
      movie: movie-events
      user: user-events
      payment: payment-events
